name: Cleanup Old Images

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Cleanup Script
      run: ci/cleanup_images.sh

    - name: Run With DockerHub Token
      uses: rapidsai/shared-actions/dockerhub-script@main
      with:
        DOCKERHUB_USER: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
        DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
        script: ci/cleanup_images.sh
