name: Nightly RAPIDS Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # 5am UTC / 1am EST

# the static `nightly` string is needed to differentiate
# this concurrency config from similar configs that exist
# in called workflows, which causes problems
concurrency:
  group: nightly-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-run-info:
    uses: ./.github/workflows/get-run-info.yaml
    secrets: inherit
    with:
      branch: branch-22.10
      repos: >-
        rapidsai/rmm
        rapidsai/cudf
  rmm-build:
    needs: get-run-info
    uses: rapidsai/rmm/.github/workflows/build.yaml@branch-22.10
    secrets: inherit
    with:
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.rmm }}
  rmm-tests:
    needs: [get-run-info, rmm-build]
    uses: rapidsai/rmm/.github/workflows/test.yaml@branch-22.10
    secrets: inherit
    with:
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.rmm }}
