name: Nightly RAPIDS Pipeline

on:
  workflow_dispatch:
  # enable cron once everything is working correctly
  # schedule:
  #   - cron: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-shas:
    uses: ./.github/workflows/get-shas.yaml
    secrets: inherit
    with:
      branch: branch-22.10
      repos: >-
        rapidsai/rmm
        rapidsai/cudf
  rmm:
    needs: [get-shas]
    uses: rapidsai/rmm/.github/workflows/branch-workflow.yaml@update-nightly-workflow
    secrets: inherit
    with:
      branch: ${{ fromJSON(needs.get-shas.outputs.shas).branch }}
      sha: ${{ fromJSON(needs.get-shas.outputs.shas).shas.rmm }}
