name: Nightly RAPIDS Pipeline

on:
  workflow_dispatch:
  # enable cron once everything is working correctly
  # schedule:
  #   - cron: ''

concurrency:
  group: nightly-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-run-info:
    uses: ./.github/workflows/get-run-info.yaml
    secrets: inherit
    with:
      branch: branch-22.10
      repos: >-
        rapidsai/rmm
        rapidsai/cudf
  rmm:
    needs: get-run-info
    uses: rapidsai/rmm/.github/workflows/branch-workflow.yaml@update-nightly-workflow
    secrets: inherit
    with:
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.rmm }}
