name: Nightly RAPIDS Pipeline

on:
  workflow_dispatch:
  # enable cron once everything is working correctly
  # schedule:
  #   - cron: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rmm:
    uses: rapidsai/rmm/.github/workflows/nightly-workflow.yaml@gha
    secrets: inherit
    with:
      REF: gha
