name: RAPIDS Pip Wheel Pipeline

on:
  workflow_dispatch:
    inputs:
      rapids-versioneer-override:
        type: string
      ucx-versioneer-override:
        type: string
      build-tag:
        type: string
  schedule:
    - cron: "0 5 * * *" # 5am UTC / 1am EST

# the static `nightly` string is needed to differentiate
# this concurrency config from similar configs that exist
# in called workflows, which causes problems
concurrency:
  group: pip-wheels-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-run-info:
    uses: ./.github/workflows/get-run-info.yaml
    secrets: inherit
    with:
      branch: branch-22.12
      repos: >-
        rapidsai/rmm
        rapidsai/cudf
        rapidsai/raft
        rapidsai/cugraph
        rapidsai/cuml

  rmm-wheel:
    needs: get-run-info

    uses: rapidsai/rmm/.github/workflows/wheels.yml@branch-22.12
    secrets: inherit
    with:
      versioneer-override: ${{ inputs.rapids-versioneer-override }}
      build-tag: ${{ inputs.build-tag }}
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.rmm }}

  cudf-wheel:
    needs: get-run-info

    uses: rapidsai/cudf/.github/workflows/wheels.yml@branch-22.12
    secrets: inherit
    with:
      versioneer-override: ${{ inputs.rapids-versioneer-override }}
      build-tag: ${{ inputs.build-tag }}
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.cudf }}

  raft-wheel:
    needs: get-run-info

    uses: rapidsai/raft/.github/workflows/wheels.yml@branch-22.12
    secrets: inherit
    with:
      versioneer-override: ${{ inputs.rapids-versioneer-override }}
      build-tag: ${{ inputs.build-tag }}
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.raft }}

  cugraph-wheel:
    needs: get-run-info

    uses: rapidsai/cugraph/.github/workflows/wheels.yml@branch-22.12
    secrets: inherit
    with:
      versioneer-override: ${{ inputs.rapids-versioneer-override }}
      build-tag: ${{ inputs.build-tag }}
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.cugraph }}

  cuml-wheel:
    needs: get-run-info

    uses: rapidsai/cuml/.github/workflows/wheels.yml@branch-22.12
    secrets: inherit
    with:
      versioneer-override: ${{ inputs.rapids-versioneer-override }}
      build-tag: ${{ inputs.build-tag }}
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.cuml }}

  # ucx-py doesn't use the same branch name as other RAPIDS projects
  get-run-info-ucx-py:
    uses: ./.github/workflows/get-run-info.yaml
    secrets: inherit
    with:
      branch: branch-0.29
      repos: >-
        rapidsai/ucx-py

  ucx-py-wheel:
    needs: get-run-info-ucx-py

    uses: rapidsai/ucx-py/.github/workflows/wheels.yml@branch-0.29
    secrets: inherit
    with:
      versioneer-override: ${{ inputs.ucx-versioneer-override }}
      build-tag: ${{ inputs.build-tag }}
      branch: ${{ fromJSON(needs.get-run-info-ucx-py.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info-ucx-py.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info-ucx-py.outputs.obj).shas.ucx-py }}
